name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to public NPM registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 18
          registry-url: https://registry.npmjs.org
          scope: '@zaiusinc'
      - name: Install dependencies
        run: yarn install
      - name: Publish
        run: |
          yarn rollup -c
          yarn pack
#        run: yarn publish --verbose --access public --registry https://registry.npmjs.org
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.npmJSToken }}
      - name: Unpack
        run: tar -zxvf zaiusinc-web-sdk-v1.0.0.tgz
