name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to public NPM registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
